language: python
python:
  - "3.3"
install:
  - pip install -r requirements-travis.txt
  - pip install coveralls
  - pip install .
script: coverage run `which django-admin.py` test halld.test --settings=halld.test_site.settings_sqlite3
after+success:
  - coveralls
