language: python
python:
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements-travis.txt
  - pip install coveralls mock
  - python -c "import enum" 2&>1 > /dev/null || pip install enum34
script: PYTHONPATH=. coverage run --source=. `which django-admin.py` test halld.test --settings=halld.test_site.settings_sqlite3
after_script:
  - coveralls
